In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../csv/signes.csv', sep=',')

In [3]:
data

,nom_video,EAR_left_0,EAR_right_0,EAR_mean_0,MAR_0,EBR_0,PERCLOS_0,HOP_gd_0,HOP_hb_0,EAR_left_1,...,HOP_hb_873,EAR_left_874,EAR_right_874,EAR_mean_874,MAR_874,EBR_874,PERCLOS_874,HOP_gd_874,HOP_hb_874,classe
0,2#kss#6-7#F#rldd#53-5#017.mp4,0.229774,0.225158,0.227466,0.231624,0,0.0,90.007700,3.178414,0.233630,...,8.444488,0.277807,0.257931,0.267869,0.287488,0,7.085714,90.005754,8.431895,2
1,3#kss#8-9#F#rldd#59-10#013.mp4,0.168676,0.142410,0.155543,0.309444,0,100.0,90.019022,2.567350,0.159321,...,1.255741,0.296405,0.325286,0.310846,0.295285,0,12.800000,89.985683,1.388983,3
2,1#kss#1-3#F#rldd#01-0#005.mp4,0.269899,0.260122,0.265010,0.384953,0,0.0,89.967157,0.669483,0.188706,...,1.124620,0.278992,0.250206,0.264599,0.387378,0,4.914286,90.049325,1.271968,1

In [6]:
data = data.drop(columns="nom_video")
data

,EAR_left_0,EAR_right_0,EAR_mean_0,MAR_0,EBR_0,PERCLOS_0,HOP_gd_0,HOP_hb_0,EAR_left_1,EAR_right_1,...,HOP_hb_873,EAR_left_874,EAR_right_874,EAR_mean_874,MAR_874,EBR_874,PERCLOS_874,HOP_gd_874,HOP_hb_874,classe
0,0.185283,0.224274,0.204779,0.304471,0,0.0,90.034640,2.853962,0.293654,0.361263,...,2.734133,0.271779,0.338344,0.305061,0.301642,0,4.228571,90.029658,2.602719,2
1,0.261595,0.329887,0.295741,0.339491,0,0.0,90.029494,2.839198,0.257767,0.327007,...,3.151807,0.271582,0.341480,0.306531,0.342457,1,5.257143,90.033424,3.206145,2
2,0.260572,0.332268,0.296420,0.324355,0,0.0,90.028459,2.934850,0.270122,0.341176,...,3.378259,0.268303,0.342254,0.305278,0.326599,0,6.285714,90.032484,3.233847,2
3,0.302635,0.371240,0.336937,0.332513,0,0.0,90.035682,2.558879,0.281124,0.354641,...,3.145728,0.261654,0.332241,0.296948,0.339726,0,5.142857,90.031556,3.144989,2
4,0.271421,0.342892,0.307156,0.340649,0,0.0,90.033886,3.458529,0.262958,0.335374,...,3.453822,0.270873,0.338745,0.304809,0.331150,1,5.942857,90.027404,3.337329,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,0.301352,0.335149,0.318250,0.329033,0,0.0,90.006472,10.063313,0.297381,0.333054,...,5.224529,0.307979,0.330306,0.319143,0.333415,0,5.028571,89.996996,5.199434,3
3744,0.263395,0.277054,0.270225,0.319046,0,0.0,89.993964,3.046364,0.284345,0.296270,...,3.507403,0.265247,0.280156,0.272701,0.327881,1,7.542857,90.001202,3.517212,3
3745,0.295671,0.312802,0.304236,0.337187,0,0.0,89.994505,3.759701,0.296414,0.307268,...,2.898542,0.306762,0.315595,0.311178,0.312778,0,7.657143,89.996732,2.899754,3
3746,0.290461,0.299336,0.294899,0.316938,0,0.0,89.994743,2.736236,0.287058,0.294691,...,1.719397,0.302351,0.314550,0.308451,0.324838,0,5.371429,89.998138,1.667383,3
3747,0.315528,0.328288,0.321908,0.314881,0,0.0,89.995562,1.601131,0.317669,0.327089,...,1.673243,0.296233,0.307690,0.301961,0.329956,0,8.228571,90.000438,1.640989,3

In [7]:
y = data["classe"]
data = data.drop(columns="classe")

In [8]:
# réorganiser les données par ordre alphanumérique
data = data.reindex(sorted(data.columns, key=lambda x: ("_".join(x.split("_")[:-2]),int(x.split("_")[-1]))), axis=1)
data

,MAR_0,EBR_0,PERCLOS_0,MAR_1,EBR_1,PERCLOS_1,MAR_2,EBR_2,PERCLOS_2,MAR_3,...,HOP_gd_870,HOP_hb_870,HOP_gd_871,HOP_hb_871,HOP_gd_872,HOP_hb_872,HOP_gd_873,HOP_hb_873,HOP_gd_874,HOP_hb_874
0,0.304471,0,0.0,0.302388,0,0.0,0.308048,0,0.0,0.314971,...,90.026911,2.630427,90.028650,2.562311,90.028872,2.474550,90.029674,2.734133,90.029658,2.602719
1,0.339491,0,0.0,0.339676,0,0.0,0.334132,0,0.0,0.336826,...,90.033804,3.160988,90.033864,3.129735,90.033474,3.074948,90.033425,3.151807,90.033424,3.206145
2,0.324355,0,0.0,0.343323,0,0.0,0.340262,0,0.0,0.340365,...,90.033149,3.144147,90.032514,3.162373,90.030770,3.171552,90.032490,3.378259,90.032484,3.233847
3,0.332513,0,0.0,0.329088,0,0.0,0.330481,0,0.0,0.333449,...,90.033028,3.191443,90.032083,3.183189,90.032275,3.185694,90.031514,3.145728,90.031556,3.144989
4,0.340649,0,0.0,0.330598,0,0.0,0.329415,0,0.0,0.328608,...,90.026637,3.271469,90.026240,3.393975,90.026308,3.338179,90.026584,3.453822,90.027404,3.337329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,0.329033,0,0.0,0.353256,0,0.0,0.353490,0,0.0,0.352123,...,89.996983,5.221523,89.997154,5.254045,89.996670,5.214634,89.996844,5.224529,89.996996,5.199434
3744,0.319046,0,0.0,0.324059,0,0.0,0.326737,0,0.0,0.327352,...,89.997021,3.192068,89.997648,3.467328,89.997044,3.662353,89.998948,3.507403,90.001202,3.517212
3745,0.337187,0,0.0,0.321541,0,0.0,0.321100,0,0.0,0.322156,...,89.997240,2.918108,89.997202,2.858141,89.996934,2.885675,89.996687,2.898542,89.996732,2.899754
3746,0.316938,0,0.0,0.320622,0,0.0,0.321293,0,0.0,0.319762,...,89.997738,1.753995,89.997757,1.761284,89.998218,1.753670,89.998200,1.719397,89.998138,1.667383
3747,0.314881,0,0.0,0.315913,0,0.0,0.315757,0,0.0,0.318361,...,90.000308,1.708079,89.999829,1.663802,89.999820,1.798864,90.000365,1.673243,90.000438,1.640989

In [9]:
# add the class column
data["classe"] = y

In [10]:
data

,MAR_0,EBR_0,PERCLOS_0,MAR_1,EBR_1,PERCLOS_1,MAR_2,EBR_2,PERCLOS_2,MAR_3,...,HOP_hb_870,HOP_gd_871,HOP_hb_871,HOP_gd_872,HOP_hb_872,HOP_gd_873,HOP_hb_873,HOP_gd_874,HOP_hb_874,classe
0,0.304471,0,0.0,0.302388,0,0.0,0.308048,0,0.0,0.314971,...,2.630427,90.028650,2.562311,90.028872,2.474550,90.029674,2.734133,90.029658,2.602719,2
1,0.339491,0,0.0,0.339676,0,0.0,0.334132,0,0.0,0.336826,...,3.160988,90.033864,3.129735,90.033474,3.074948,90.033425,3.151807,90.033424,3.206145,2
2,0.324355,0,0.0,0.343323,0,0.0,0.340262,0,0.0,0.340365,...,3.144147,90.032514,3.162373,90.030770,3.171552,90.032490,3.378259,90.032484,3.233847,2
3,0.332513,0,0.0,0.329088,0,0.0,0.330481,0,0.0,0.333449,...,3.191443,90.032083,3.183189,90.032275,3.185694,90.031514,3.145728,90.031556,3.144989,2
4,0.340649,0,0.0,0.330598,0,0.0,0.329415,0,0.0,0.328608,...,3.271469,90.026240,3.393975,90.026308,3.338179,90.026584,3.453822,90.027404,3.337329,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,0.329033,0,0.0,0.353256,0,0.0,0.353490,0,0.0,0.352123,...,5.221523,89.997154,5.254045,89.996670,5.214634,89.996844,5.224529,89.996996,5.199434,3
3744,0.319046,0,0.0,0.324059,0,0.0,0.326737,0,0.0,0.327352,...,3.192068,89.997648,3.467328,89.997044,3.662353,89.998948,3.507403,90.001202,3.517212,3
3745,0.337187,0,0.0,0.321541,0,0.0,0.321100,0,0.0,0.322156,...,2.918108,89.997202,2.858141,89.996934,2.885675,89.996687,2.898542,89.996732,2.899754,3
3746,0.316938,0,0.0,0.320622,0,0.0,0.321293,0,0.0,0.319762,...,1.753995,89.997757,1.761284,89.998218,1.753670,89.998200,1.719397,89.998138,1.667383,3
3747,0.314881,0,0.0,0.315913,0,0.0,0.315757,0,0.0,0.318361,...,1.708079,89.999829,1.663802,89.999820,1.798864,90.000365,1.673243,90.000438,1.640989,3

In [17]:
# création du dataframe final
arrays = [np.array([i for i in range(0,data.shape[0]) for j in range(0, 875)]), np.array([i for j in range(0, data.shape[0]) for i in range(0,875)])]
index = pd.MultiIndex.from_arrays(arrays, names=('instance', 'frame'))
final_data = pd.DataFrame(0, index = ["MAR", "EAR_left", "EAR_right", "EAR_mean", "HOP_gd", "HOP_hb", "EBR", "PERCLOS", "classe"], columns=index)
final_data = final_data.T

In [18]:
final_data

                MAR  EAR_left  EAR_right  EAR_mean  HOP_gd  HOP_hb  EBR  \
instance frame
0        0        0         0          0         0       0       0    0
         1        0         0          0         0       0       0    0
         2        0         0          0         0       0       0    0
         3        0         0          0         0       0       0    0
         4        0         0          0         0       0       0    0
...             ...       ...        ...       ...     ...     ...  ...
3747     870      0         0          0         0       0       0    0
         871      0         0          0         0       0       0    0
         872      0         0          0         0       0       0    0
         873      0         0          0         0       0       0    0
         874      0         0          0         0       0       0    0

                PERCLOS  classe
instance frame
0        0            0       0
         1            0       0
         2            0       0
         3            0       0
         4            0       0
...                 ...     ...
3747     870          0       0
         871          0       0
         872          0       0
         873          0       0
         874          0       0

[3279500 rows x 9 columns]

In [21]:
d = data[[f"MAR_{i}" for i in range(0,875)]]
d = d.to_numpy().flatten()
d.shape

(3279500,)

In [24]:
for sign in ["MAR", "EAR_left", "EAR_right", "EAR_mean", "HOP_gd", "HOP_hb", "EBR", "PERCLOS"]:
    data2 = data[[f"{sign}_{i}" for i in range(0,875)]]
    d = data2.to_numpy()
    d = d.flatten()
    final_data[sign] = d
    
final_data
# , "EBR", "PERCLOS"

                     MAR  EAR_left  EAR_right  EAR_mean     HOP_gd    HOP_hb  \
instance frame
0        0      0.304471  0.185283   0.224274  0.204779  90.034640  2.853962
         1      0.302388  0.293654   0.361263  0.327459  90.029065  2.758461
         2      0.308048  0.267476   0.338525  0.303000  90.031310  3.453699
         3      0.314971  0.267631   0.336078  0.301855  90.029595  3.279016
         4      0.328905  0.262299   0.334176  0.298237  90.029725  3.619524
...                  ...       ...        ...       ...        ...       ...
3747     870    0.334571  0.300171   0.311573  0.305872  90.000308  1.708079
         871    0.334997  0.297928   0.309422  0.303675  89.999829  1.663802
         872    0.333441  0.298444   0.309691  0.304068  89.999820  1.798864
         873    0.330041  0.297926   0.309404  0.303665  90.000365  1.673243
         874    0.329956  0.296233   0.307690  0.301961  90.000438  1.640989

                EBR   PERCLOS  classe
instance frame
0        0        0  0.000000       0
         1        0  0.000000       0
         2        0  0.000000       0
         3        0  0.000000       0
         4        0  0.000000       0
...             ...       ...     ...
3747     870      0  8.266361       0
         871      0  8.256881       0
         872      0  8.247423       0
         873      0  8.237986       0
         874      0  8.228571       0

[3279500 rows x 9 columns]

In [25]:
classe = [i for i in y for j in range(0,875)]

In [26]:
final_data["classe"] = classe
final_data

                     MAR  EAR_left  EAR_right  EAR_mean     HOP_gd    HOP_hb  \
instance frame
0        0      0.304471  0.185283   0.224274  0.204779  90.034640  2.853962
         1      0.302388  0.293654   0.361263  0.327459  90.029065  2.758461
         2      0.308048  0.267476   0.338525  0.303000  90.031310  3.453699
         3      0.314971  0.267631   0.336078  0.301855  90.029595  3.279016
         4      0.328905  0.262299   0.334176  0.298237  90.029725  3.619524
...                  ...       ...        ...       ...        ...       ...
3747     870    0.334571  0.300171   0.311573  0.305872  90.000308  1.708079
         871    0.334997  0.297928   0.309422  0.303675  89.999829  1.663802
         872    0.333441  0.298444   0.309691  0.304068  89.999820  1.798864
         873    0.330041  0.297926   0.309404  0.303665  90.000365  1.673243
         874    0.329956  0.296233   0.307690  0.301961  90.000438  1.640989

                EBR   PERCLOS  classe
instance frame
0        0        0  0.000000       2
         1        0  0.000000       2
         2        0  0.000000       2
         3        0  0.000000       2
         4        0  0.000000       2
...             ...       ...     ...
3747     870      0  8.266361       3
         871      0  8.256881       3
         872      0  8.247423       3
         873      0  8.237986       3
         874      0  8.228571       3

[3279500 rows x 9 columns]

In [31]:
ebr = final_data["EBR"].to_numpy().flatten()
np.unique(ebr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [27]:
final_data.to_csv("final_ml.csv")